application: laddrs
version: 6-0-0
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.2"
- name: webapp2
  version: "2.5.2"
 
builtins:
- appstats: on

inbound_services:
- channel_presence
- warmup

handlers:
- url: /s
  static_dir: s

- url: /favicon.ico
  static_files: s/sc2replay-icon.png
  upload: s/sc2replay-icon.png

- url: /robots.txt
  static_files: s/robots.txt
  upload: s/robots.txt

- url: /_ah/channel/connected/
  script: channel.app

- url: /_ah/channel/disconnected/
  script: channel.app

- url: /channel/.*
  script: channel.app
  login: required

- url: /cron/chat-keep-alive
  script: channel.app

- url: /create_ladder
  script: create_ladder.app
  login: required

- url: /ladder/.*
  script: ladder.app

- url: /manage_ladder/.*
  script: ladder.app

- url: /join_ladder/.*
  script: join_ladder.app

- url: /upload/.*
  script: upload.app

- url: /replay_debug
  script: replay_debug.app
  login: required

- url: /download/.*
  script: download.app

- url: /faq
  script: faq.app

- url: /_ah/warmup
  script: main.app

- url: /
  script: main.app
