application: laddrs
version: 5-0-0
runtime: python
api_version: 1

builtins:
- appstats: on

inbound_services:
- channel_presence
- warmup

handlers:
- url: /s
  static_dir: s

- url: /favicon.ico
  static_files: s/sc2replay-icon.png
  upload: s/sc2replay-icon.png

- url: /robots.txt
  static_files: s/robots.txt
  upload: s/robots.txt

- url: /_ah/channel/connected/
  script: channel.py

- url: /_ah/channel/disconnected/
  script: channel.py

- url: /channel/.*
  script: channel.py
  login: required

- url: /cron/chat-keep-alive
  script: channel.py

- url: /create_ladder
  script: create_ladder.py
  login: required

- url: /ladder/.*
  script: ladder.py

- url: /manage_ladder/.*
  script: ladder.py

- url: /join_ladder/.*
  script: join_ladder.py

- url: /upload/.*
  script: upload.py

- url: /replay_debug
  script: replay_debug.py
  login: required

- url: /download/.*
  script: download.py

- url: /faq
  script: faq.py

- url: /_ah/warmup
  script: main.py

- url: /
  script: main.py
